### ISSUE TITLE
Ghost terminals in the background

### ISSUE THREAD

**Issue by bboure** [vercel/hyper#2719]
I have a semi transparent background and after some time of use I can see some "ghosts" of old commands/outputs in the background.

![image](https://user-images.githubusercontent.com/7089997/36723248-06b6c414-1bb0-11e8-8545-631a3fbc7e20.png)

I was not able to reproduce it yet. Not sure if it happens in some particular cases or just randomly.

It looks like it's there are old DOM elements in the background.

**Comment by DuckThom** [comment]
I can confirm this happens on a clean install of both 1.4.8 and 2.0.0-canary.14.
Steps to reproduce:

1.  Install 1.4.8 or 2.0.0-canary.14.
2. Edit `.hyper.js`, set the terminal background color to `rgba(0,0,0,0.5)` (or another transparent value)
3. To make sure the config is loaded properly, I restarted Hyper but this may be optional.
4. Make sure there is some output on the screen (ie. `cat .hyper.js`)
5. Resize the Hyper screen
6. Clean the terminal with `Ctrl+L` to see the "ghost" effect

When the Hyper screen is not in focus, the ghost text disappears. This is also the case if the Hyper screen is resized again.
The ghosted text will be the text that was on-screen when the terminal was being resized.

**Comment by bboure** [comment]
thanks @DuckThom  +1 on reproduction steps. I knew it had to do with cleaning the terminal since I use `cmd-K` all the time.

**Comment by Lucretius** [comment]
Comparing this behavior to what happens in iTerm2/Terminal upon clear:  

In iTerm2 the pane is cleared by simply scrolling down until the previous text disappears.  The basic mac Terminal app does something similar, but just scrolls a full window size down instead of just the few lines that iTerm does.  That scrolling behavior does not seem to happen in Hyper, instead all previous commands appear to be hidden instead of this scrolling effect.  I'm digging into the render cycle to try and pinpoint this but my guess is that this is causing the ghosting effect.

**Comment by Stanzilla** [comment]
Hey there, to verify if this is indeed a Hyper issue or upstream at https://github.com/xtermjs/xterm.js/ could you please test if another xterm.js powered terminal shows the same problem you are experiencing? I suggest using https://github.com/Microsoft/vscode for testing. Thanks!

**Comment by Jaden-Giordano** [comment]
Any updates on this?

**Comment by chabou** [comment]
It should be fixed by our just-released canary: https://github.com/zeit/hyper/releases/tag/2.1.0-canary.2

Can you confirm this?

**Comment by Jaden-Giordano** [comment]
I'm still getting the ghost text when the window isn't focused on 2.1.0-canary.2. Running on OSX High Sierra.

**Comment by agypsydiver** [comment]
Any updates on this? Willing to contribute.

**Comment by LabhanshAgrawal** [comment]
@agypsydiver can you try the latest [ci build](https://github.com/vercel/hyper/actions/runs/151770461) and check if it's still happening.

**Comment by agypsydiver** [comment]
@LabhanshAgrawal Have been using that exact build for a week now, no ghosts! 😄
