### ISSUE TITLE
Keep getting � symbols when using Yarn

### ISSUE THREAD

**Issue by mdizo** [vercel/hyper#4199]
- [x] I am on the [latest](https://github.com/zeit/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/zeit/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Hyper.app version**: 3.0.2
- **Link of a [Gist](https://gist.github.com/mdizo/40ed27acab76709adb8a87564492b655) with the contents of your .hyper.js**: [.hyper.js](https://gist.github.com/mdizo/40ed27acab76709adb8a87564492b655)
- **Relevant information from devtools** _(CMD+ALT+I on macOS, CTRL+SHIFT+I elsewhere)_:  N/A
- **The issue is reproducible in vanilla Hyper.app**:  Is Vanilla

## Issue

![Hyper_btmDbsebYT](https://user-images.githubusercontent.com/12964726/73095313-2631c080-3e97-11ea-8102-13407b3be855.png)

Note: This is on a fresh install of Windows 10.

**Comment by LabhanshAgrawal** [comment]
I'm able to see the emojis with yarn (Hyper 3.0.2) 

![Annotation 2020-01-25 134549](https://user-images.githubusercontent.com/16598275/73118382-65384280-3f79-11ea-8457-e51355a38164.png)
You're getting the ✨ symbol at the end but not other symbols, It might be a fonts issue.
I have fonts configured as `fontFamily: '"Source Code Pro", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace'`

**Comment by LabhanshAgrawal** [comment]
P.S. I am using powershell 6, not cmd. if that might be relevant.

**Comment by mdizo** [comment]
Thanks for replying back. I've tried using different fonts, still no differences. It seems the microsoft emoji font is still working fine when used in browsers:
![firefox_NxeSspfUSS](https://user-images.githubusercontent.com/12964726/73119830-5914ab00-3fa2-11ea-88e9-11f1c66f6f36.png)

It seems weird to me why only one emoji font works and the other don't.

**Comment by mdizo** [comment]
Found related issue #3113

**Comment by LabhanshAgrawal** [comment]
I tried again, using your config and the Jetbrains font (also tried with the default config), still faced no issue.
You can try out the latest canary build from [here](https://github.com/zeit/hyper/suites/415124596/artifacts/1282439)
There's currently a bug in canary with cursorColor and selectionColor, using rgba(), you will have to use hex colors. But you should be able to test the emoji thing easily

**Comment by mdizo** [comment]
Still facing the same issues with vanilla config 😢 
Thanks for trying to help though.

**Comment by LabhanshAgrawal** [comment]
Did you try the canary build?

**Comment by LabhanshAgrawal** [comment]
the bugs I mentioned should be fixed soon.

**Comment by mdizo** [comment]
> 
> 
> Did you try the canary build?

Yep. Even tried forking the branch and build my own executable. Still the same problem.

**Comment by LabhanshAgrawal** [comment]
I'm out of ideas then 😔.

**Comment by petercr** [comment]
Yeah I'm having the same issue too, where almost all of the emojis are not showing up on Windows 10 with Hyper Terminal. 
I have these plugin's running:
- `hyperpower`
- `hyper-night-owl`

They seem to work everywhere else, but I'm also running Windows Build 19041.84 so it could also be a Windows issue 🤷‍♂

**Comment by LabhanshAgrawal** [comment]
@mdizo @petercr 
We've recently added the xterm unicode plugin, which may fix this
Can you try the latest [ci build](https://github.com/vercel/hyper/actions/runs/153185087) once and check if it works

**Comment by LabhanshAgrawal** [comment]
@petercr did it work properly for you?

**Comment by petercr** [comment]
@LabhanshAgrawal Sorry I haven't had a chance to test it out yet. I have been really busy. 😅

I will try it out today, and let you know 👍

**Comment by petercr** [comment]
@LabhanshAgrawal So I checked out the latest build like you asked. It seemed to work great with `oh-my-zsh` and a custom Nerd Font. So I am no longer having this issue with the 3.1.0 build 👍
