### ISSUE TITLE
Performance + Animation Lags on 3.1.0 (stable)

### ISSUE THREAD

**Issue by jrodl3r** [vercel/hyper#5754]
- [x] I am on the [latest](https://github.com/vercel/hyper/releases/latest) Hyper.app version
- [x] I have searched the [issues](https://github.com/vercel/hyper/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: MacOS Big Sur 11.3.1 (20E241)
- **Hyper.app version**: 3.1.0 stable
- **Link of a [Gist](https://gist.github.com/) with the contents of your .hyper.js**: http://pastie.org/p/2BlzawsQ9LF9hg7WzMWSrW
- **The issue is reproducible in vanilla Hyper.app**: technically, no. but come on... this was not an issue until i was forced to upgrade.

## Issue
forced upgrade causes performance lag when using plugins.

**Comment by joaaoeu** [comment]
A simple `cd Documents` take so long... I uninstalled and installed version `3.0.2` again and it is normal, but then it updates to the `3.1.0` automatically.

**Comment by joshsylvester** [comment]
I'm having the same issue - auto-upgraded to `3.1.0`, after 5-10 minutes, hyper is so laggy it's unusable. I type any command into the console - and it takes up 20-30 seconds to display what i had typed.  normal command that should return in a second or two take 2-3 minutes to run.

**Comment by LabhanshAgrawal** [comment]
Can you try removing all plugins and adding them back one by one, to see if it's due to any particular one.
hyper-statusline was causing some issues for me earlier.

**Comment by stephanschubert** [comment]
[`hyperline` is the culprit here](https://github.com/Hyperline/hyperline/issues/198) (at least from the list of my plugins).

**Comment by jackvhall** [comment]
I'm noticing that after the upgrade, Hyper Helper (renderer) process has very high CPU usage.

**Comment by industriousparadigm** [comment]
+1, removing hyperline removes the laggy input for me on `3.1.0` running on macOS Big Sur.

**Comment by radmedov** [comment]
+1 very slow after the upgrade. Downgrade to 3.0.2 resolves the issues

**Comment by mitchwd** [comment]
+1 Removing the `hyper-statusline` plugin resolved the issue for me. Ticketed here: https://github.com/henrikdahl/hyper-statusline/issues/96

**Comment by LabhanshAgrawal** [comment]
@jrodl3r can you post your config again, that link is not working.

**Comment by LabhanshAgrawal** [comment]
Both hyperline and hyper-statusline are causing issues at the moment, both of these are using setInterval with small values for either getting time, system resources, etc. and spawning child processes very frequently.

**Comment by RenanSgorlom** [comment]
can confirm after the update `hyper-statusline` was causing lag, removing it fixes the issue even on hyper 3.1.1
hopefully they fix the issue soon

**Comment by LabhanshAgrawal** [comment]
> Both hyperline and hyper-statusline are causing issues at the moment, both of these are using setInterval with small values for either getting time, system resources, etc. and spawning child processes very frequently.

This along with an issue in electron https://github.com/electron/electron/issues/26143 is giving us the lag.

**Comment by LabhanshAgrawal** [comment]
Can you all try out the build from https://github.com/vercel/hyper/actions/runs/1049604539 to see if there's any improvement in perf.

**Comment by LabhanshAgrawal** [comment]
Can you all try out the build from https://github.com/vercel/hyper/actions/runs/1049653907 to see if there's any improvement in perf.

**Comment by bfaulk96** [comment]
> Can you all try out the build from https://github.com/vercel/hyper/actions/runs/1049653907 to see if there's any improvement in perf.

Using `Hyper-3.1.0-canary.6-mac-x64.dmg` on MacOS Big Sur, this did indeed seem to fix the problem. No lag running the canary version with `hyperline` enabled 👍

**Comment by joaaoeu** [comment]
Yep, here the `Hyper 3.1.0-canary.6` is ok as well `MacOS Big Sur 11.4` 👍🏻

**Comment by LabhanshAgrawal** [comment]
There'd need to be some updates in the plugins though. Doing `exec` or `spawn` from renderer is discouraged, it should be done from the main process ideally. Doing it from the renderer is slowly being phased out.
The electron issue mentioned that there was some difference between signed vs unsigned builds. The one I'd mentioned earlier is unsigned.
Can you try the build from https://github.com/vercel/hyper/actions/runs/1051187521#artifacts too? It's signed and so will help confirm the fix for now.

**Comment by joaaoeu** [comment]
@LabhanshAgrawal this last build that you sent (https://github.com/vercel/hyper/actions/runs/1051187521#artifacts) still with the lag when `hyper-statusline` plugin is enabled 😞

**Comment by joaaoeu** [comment]
I'm not sure if something changed from the other build (https://github.com/vercel/hyper/actions/runs/1049653907), but I tested again and this one is fixed...

**Comment by LabhanshAgrawal** [comment]
@joaaoeu the difference is that one is signed and other isn't. IIRC it's something due to changes in Big Sur. Many electron apps are using `codesign --remove ....` to remove the signature and fix the performance hit, after users install it. We might also need to do something similar.

**Comment by LabhanshAgrawal** [comment]
since downgrading electron might not be feasible as the bug is still there in signed builds, we can instead use IPC to do exec etc. in main process.
Test out the build from #5803 https://github.com/vercel/hyper/actions/runs/1077170228#artifacts
it should be good enough i guess until the issue is fixed in electron.

**Comment by joaaoeu** [comment]
With this build it still with a small lag if the `hyper-statusline` plugin is enabled, but less than the current version.

**Comment by bfaulk96** [comment]
I'm seeing the same behavior using that @joaaoeu mentioned when using the `hyperline` plugin. Less lag, but still quite laggy.

**Comment by JJJ** [comment]
Not seeing with 3.3.0. OK to close IMO.
