### ISSUE TITLE
Text pasted has white background on white

### ISSUE THREAD

**Issue by jdsimcoe** [vercel/hyper#819]
When I paste any text in to Hyper.app the pasted text shows white background on white:

![screen shot 2016-10-07 at 1 38 37 pm](https://cloud.githubusercontent.com/assets/275617/19204797/aa7f8d68-8c93-11e6-864c-02790feb1f9d.png)

I have no plugins.

**Comment by flybayer** [comment]
Does this still happen if you temporarily comment out all of your custom configuration and plugins?

**Comment by dennisroethig** [comment]
fwiw I saw that behaviour too a few times, after trying to replicate it and restarting Hyper multiple times it *seems* to be fine now ¯\_(ツ)_/¯

**Comment by iamstarkov** [comment]
have seen this today

**Comment by jdsimcoe** [comment]
@flybayer I commented everything out and it still happens.

**Comment by muescha** [comment]
the white on white in nano editor is without any plugin enabled. a fresh install

**Comment by CodeTheory** [comment]
@muescha I can reproduce.

**Comment by jessemillar** [comment]
I can also reproduce. If I change my `foregroundColor` to be partially transparent (e.g. `'rgba(255, 255, 255, 0.75)'`), I can at least read the highlighted text, but it's far from perfect.

**Comment by LukasMa** [comment]
I can reproduce:
Hyper  + bash = OK!
Hyper  + zsh    = NOT OK!
iTerm2 + bash = OK!
iTerm2 + zsh   = OK!
**(No modifications/plugins whatsoever!)**

**Comment by nicholasruggeri** [comment]
Fresh install. White on white in nano editor
![screenshot 2016-10-14 17 42 38](https://cloud.githubusercontent.com/assets/999162/19393592/a6b244b2-9235-11e6-914e-e71179edc7c4.png)

**Comment by tonybaroneee** [comment]
Fresh install, fish shell, macOS Sierra (10.12)

![image](https://cloud.githubusercontent.com/assets/844249/19411233/9ef0098a-92cb-11e6-8fd0-698e48a8bd42.png)

**Comment by knownasilya** [comment]
Also happens for text like `_my test_`, which is an issue for markdown files with `__my test__` (emphasis).

**Comment by LeonBlade** [comment]
Fresh install, same problem.  I'd rather use VIM over nano anyway.

**Comment by chriscraws** [comment]
I ran into this issue using hyper for the first time; both bash and zsh are affected for me.

**Comment by ipalindromi** [comment]
I am also experiencing this issue after a first time install with zsh on macOS Sierra.

**Comment by lordgiotto** [comment]
Same issue here with Sierra, hyper 0.8.3 and zsh.

**Comment by reneruiz** [comment]
Also affected. Sierra, hyper 0.8.3., zsh 5.2

**Comment by harryparkdotio** [comment]
Same issue here, Sierra: 10.12.1. Hyper: 0.8.3 (0.8.3.873). Also using zsh.

**Comment by svenfinke** [comment]
Same issue here... Sierra 10.12.1 + Hyper: 0.8.3.873 And I am also using zsh, with the agnostic theme. This makes Hyper pretty much unusable for me atm... 😢

**Comment by 4cm4k1** [comment]
Same issue here. 

It’s probably been mentioned before somewhere else, but here’s a temporary workaround until the bug is fixed. Just add the following lines of code in your `.hyper.js` or by clicking Preferences in the menu bar:
```js
module.exports = {
    config: {
        ...
        // custom css to embed in the terminal window (this comment is in .hyper.js by default)
        // below is temp workaround for nano & copy/paste whiteouts
        termCSS: 'span { background-color: transparent !important; }',
        ...
    }
}
```

Works for me until it gets fixed. 😀

**Comment by ppot** [comment]
This doesn't happen to me on resent master

**Comment by benjaminprojas** [comment]
I just downloaded hyper yesterday for the first time, no plugins, I have this issue when editing the preferences.

**Comment by jdsimcoe** [comment]
Doesn't happen anymore for me on a recent `master` build.

**Comment by ppot** [comment]
@CodeTheory  You can mark this solved in resent master!

**Comment by ppot** [comment]
Fix in #1218

**Comment by jakeNiemiec** [comment]
This has cropped up again on Hyper+Zsh after the <canvas> update. The css hack no longer works.

But fear not, you can disable this behavior on the zsh side with `unset zle_bracketed_paste`.

**Comment by txchen** [comment]
Same here with Hyper(2.0) + ZSH.
Hope the CSS hack can work again, I don't want to put hack in my .zshrc since I still like the feature.

**Comment by cacois** [comment]
even with hacking .zshrc, this bug crops up in another place:

![image](https://user-images.githubusercontent.com/347087/48019102-d5964200-e0ef-11e8-8ee6-0f316a64e437.png)
Not sure what the context is here, because its not a paste, but that white bar at the bottom looks like this in iTerm2:

![image](https://user-images.githubusercontent.com/347087/48019192-0aa29480-e0f0-11e8-868c-e5d774cd643b.png)

**Comment by jakeNiemiec** [comment]
@timothyis @ppot, please consider reopening this 🙏

**Comment by mamakawama** [comment]
Same here with Hyper(2.0) + ZSH.

**Comment by loftusa** [comment]
Having the same problem. Even uninstalled ZSH, bug persists. @timothyis  @ppot seconding @jakeNiemiec, please consider reopening

**Comment by hugofloss** [comment]
Same problem here with a fresh install of Hyper 2.0.0

**Comment by bkjoel** [comment]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/27892030/50543574-c3fb8300-0be4-11e9-9f08-7303f0f87b95.png">
I got it when searching for "color" inside `man ls` using hyper and zsh

**Comment by lotap** [comment]
I also am experiencing this issue when pasting and when create-a-react-app finds a linting error. I was able to "solve" the issue by removing the `hyper-transparent` plugin. I also noticed when I set opacity to 1 with that plugin installed, everything worked as expected. 

OSX 10.14.2
ZSH

**Comment by wbsmolen** [comment]
Seeing this on Mojave, hyper 2.1.1. Not running zsh. Not using the hyper-transparent plugin. Please consider reopening this.

**Comment by reneroth** [comment]
Reopen please, Hyper 2.1.2 with zsh

**Comment by wbsmolen** [comment]
@ppot would you consider reopening this? There appear to outstanding problems. I don't want to spam github with duplicate issues

**Comment by jakeNiemiec** [comment]
@chabou @juancampa @rauchg also seem active here and would probably have rights to reopen this issue. I agree with @wbsmolen, there is a lot of good info here that would be lost with a new issue.

Sorry for the ping, I wouldn't be such a pest if this bug wasn't such a constant obstacle. I would've made a PR myself if I had even the slightest idea how to fix this 🤔.

**Comment by ohgree** [comment]
can reproduce same issue here, with hyper-material-theme plugin, if backgroundOpacity is 1, the problem is not recurring whereas below 1, nano shows white-on-white texts and etc.

**Comment by liming-gd** [comment]
met this on hyper 2.1.2 with hyper-search (0.1.1) and verminal (1.4.3). After set opacity of  backgroundColor by 1 or uninstall verminal, everything works fine.

**Comment by lmcl90** [comment]
met this on hyper 2.1.2 with hyper-search (0.1.1) and verminal (1.4.3). After set opacity of backgroundColor by 1 or uninstall verminal, everything works fine.

**Comment by bkjoel** [comment]
Sorry to be such a nag but is there any updates on this issue? anyone maybe had success with quick & dirty fixes other than switching Hyper?

**Comment by linonetwo** [comment]
@bkjoel You can switch zsh feature off by adding `unset zle_bracketed_paste` to `.zshrc`

**Comment by ohgree** [comment]
@linonetwo It is actually not only about the pasting thing, but every white-backgrounded text, such as nano menus, less (END) text, are all affected by this bug

**Comment by linonetwo** [comment]
An upstream bug here needs help https://github.com/xtermjs/xterm.js/issues/1898

**Comment by reneroth** [comment]
for me it's fixed in the newly released v3.0.0

**Comment by linonetwo** [comment]
I'm excited about the release, but for me, this issue is not fixed.
https://github.com/robbyrussell/oh-my-zsh/issues/7832

**Comment by jakeNiemiec** [comment]
![image](https://user-images.githubusercontent.com/16782063/57232846-20cbd780-6fe3-11e9-97ed-b8e7dafc03a1.png)

It is still present on v3.0.0 for me, here is a visual for reference.

**Comment by ohgree** [comment]
Not fixed for me either. On hyper 3.0.0

**Comment by gvidon** [comment]
Still reproducible on hyper 3.0.0-canary.10 with fish.

**Comment by shash678** [comment]
Managed to get both selection and copy-paste readable by commenting out the `selectionColor` line in my `hyper.js`config file as well as adding `unset zle_bracketed_paste` to my `/.zshrc` file as mentioned above.

**Comment by shash678** [comment]
Try commenting out the `selectionColor` line in your `.hyper.js` config file as well as adding `unset zle_bracketed_paste` line to your `./zshrc`.

This made copy-pasting and selection readable for me.

**Comment by DEfusion** [comment]
Getting this on 3.0.2 stable with zsh, the workaround for zsh by @jakeNiemiec works for me at the moment.

**Comment by mazyvan** [comment]
this issue is also happening on tabs with zsh

**Comment by isanimu** [comment]
Inside the .hyper.js config, If the `backgroundColor` is set to not using alpha (ex: `#000000`), it wouldn't trigger the problem.

Setting `backgroundColor` to any color with alpha (ex: `rgba(0, 0, 0, 0.8)`) **WILL** trigger the problem if the renderer is not WebGL.

When using plugin that sets the `backgroundColor` to any color that using alpha will set the renderer as WebGL. While setting it inside the config won't, I don't know why.

I've tested it using hyper-material-theme plugin and using dummy local plugin to set the `backgroundColor` to a color with alpha, and it solve the problem because it set the renderer as WebGL.

The only problem when renderer is WebGL it would use the dedicated GPU, unless you don't have any problem with that.

@jakeNiemiec `unset zle_bracketed_paste to .zshrc` works with any renderer and solve the problem for zsh shell.

**Comment by jakeNiemiec** [comment]
I removed everything alpha/opacity related and now everything works. Thanks @isanimu!

**Comment by mvllow** [comment]
Unfortunately still having this issue. With a fresh install, highlighted text is somewhat legible (translucent white with white text) but with themes such as `hyper-website-theme` and `hyper-snazzy` the text is still white/white. I suppose it could be an issue with the themes as I've only tested a few but either way, without a theme it is still not ideal.

**Comment by Relaxself** [comment]
It's appear when I use opacity color or plugin.

**Comment by bet4it** [comment]
@Relaxself  Try [v3.1.0-canary.4](https://github.com/zeit/hyper/releases/tag/v3.1.0-canary.4)

**Comment by Relaxself** [comment]
> @Relaxself Try [v3.1.0-canary.4](https://github.com/zeit/hyper/releases/tag/v3.1.0-canary.4)

OK，I‘ll try. thx

**Comment by Relaxself** [comment]
> @Relaxself Try [v3.1.0-canary.4](https://github.com/zeit/hyper/releases/tag/v3.1.0-canary.4)

I used 3.1.0 install and fresh install ,but unfortunately, it appear an error.
when first I open hyper,the screen like this:
![image](https://user-images.githubusercontent.com/8120401/76135349-383f7b00-6061-11ea-8d93-510328e31d70.png)

then i press any key... oh my
![image](https://user-images.githubusercontent.com/8120401/76135360-4ee5d200-6061-11ea-8cc8-ddf38e9769ee.png)

my System info is:
MacOS Catalina
ZSH
and hyper use default config,no plugin and no change

**Comment by bet4it** [comment]
@Relaxself This may be another issue?

**Comment by snappy316** [comment]
Updating to 3.1.0-canary.4 seems to have fixed it! 🎉

Both the pasted text from the original issue, as well as the bug in Nano as shown in [this comment](https://github.com/zeit/hyper/issues/819#issuecomment-489646566) are now fixed!! 

(For reference, `backgroundColor: "rgba(0, 0, 0, 0.7)"` in my config was broken in 3.0.2, but was immediately fixed in the canary version.)

**Comment by OnTheRicky** [comment]
I have this problem not only when I paste text, but also when there is download bar that "scrolls over" text.

Running Hyper 3.0.2 (stable) + zsh on macOS Catalina
Renderers: Canvas (4)
Plugins: 
  hyper-search (0.4.0),
  verminal (1.5.1),
  hyperline (1.2.0)

**Comment by Mvrs** [comment]
Can confirm that this problem has been resolved in  the latest **3.1.0-canary.4** version
:partying_face:

**Comment by LabhanshAgrawal** [comment]
Based on the last comment, it seems to be fixed.
Closing this, Feel free to open a new issue if you face any problems.
